export const customerData = [
  {
    id: 1,
    name: "Aarav Sharma",
    email: "aarav@example.com",
    avatar: "https://i.pravatar.cc/150?img=1",
    totalSpent: 1420,
    orders: 18,
    loyalty: 88,
    status: "Active",
    blocked: false,
    joined: "12 Jan 2026",
  },
  {
    id: 2,
    name: "Priya Mehta",
    email: "priya@example.com",
    avatar: "https://i.pravatar.cc/150?img=2",
    totalSpent: 920,
    orders: 11,
    loyalty: 62,
    status: "VIP",
    blocked: false,
    joined: "03 Feb 2026",
  },
  {
    id: 3,
    name: "Rohan Verma",
    email: "rohan@example.com",
    avatar: "https://i.pravatar.cc/150?img=3",
    totalSpent: 250,
    orders: 4,
    loyalty: 28,
    status: "Blocked",
    blocked: true,
    joined: "18 Mar 2026",
  },
  {
    id: 4,
    name: "Simran Kaur",
    email: "simran@example.com",
    avatar: "https://i.pravatar.cc/150?img=4",
    totalSpent: 1890,
    orders: 25,
    loyalty: 96,
    status: "Premium",
    blocked: false,
    joined: "27 Apr 2026",
  },
];